#server configuration:
server:
  port: 8761
  compression:
    enabled: false
  tomcat:
    uri-encoding: UTF-8
  error:
    include-message: never

#spring configuration:
spring:
  webflux:
    base-path: /eureka
  application:
    name: api-core-ejercito-statistics-eureka-microservice
    version: 1.0.0
  messages:
    encoding: UTF-8
  version: v2.7.1
  main:
    banner-mode: log
    lazy-initialization: false

#logging configuration
logging:
  level:
    root: ${LOGGING_CONFIGURATION_APP:info}

#developer configuration:
developer:
  nickname: cbacilio

#microservice configuration:
microservice:
  key: 524be2fc-9995-4ab0-98c6-8d2e16502522
  datasource:
    name: microservice.datasource.ep.solutions
    encryption-enable: true
    encryption-key: true
  configuration:
    domain: http://localhost:8080
    type: microservice.configuration.type.json.file
  error-handler: ERROR_HANDLER_LINK_NOT_DEFINED
  messages:
    path: "/json/messages.json"
    index: "01"
